name: Deploy WordPress to Dokku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate WordPress salts
        id: salts
        run: |
          AUTH_KEY=$(openssl rand -base64 48)
          SECURE_AUTH_KEY=$(openssl rand -base64 48)
          LOGGED_IN_KEY=$(openssl rand -base64 48)
          NONCE_KEY=$(openssl rand -base64 48)
          AUTH_SALT=$(openssl rand -base64 48)
          SECURE_AUTH_SALT=$(openssl rand -base64 48)
          LOGGED_IN_SALT=$(openssl rand -base64 48)
          NONCE_SALT=$(openssl rand -base64 48)
          
          echo "::set-output name=AUTH_KEY::$AUTH_KEY"
          echo "::set-output name=SECURE_AUTH_KEY::$SECURE_AUTH_KEY"
          echo "::set-output name=LOGGED_IN_KEY::$LOGGED_IN_KEY"
          echo "::set-output name=NONCE_KEY::$NONCE_KEY"
          echo "::set-output name=AUTH_SALT::$AUTH_SALT"
          echo "::set-output name=SECURE_AUTH_SALT::$SECURE_AUTH_SALT"
          echo "::set-output name=LOGGED_IN_SALT::$LOGGED_IN_SALT"
          echo "::set-output name=NONCE_SALT::$NONCE_SALT"

      - name: Set WordPress config
        run: |
          dokku config:set --no-restart wordpress \
            WP_AUTH_KEY="${{ steps.salts.outputs.AUTH_KEY }}" \
            WP_SECURE_AUTH_KEY="${{ steps.salts.outputs.SECURE_AUTH_KEY }}" \
            WP_LOGGED_IN_KEY="${{ steps.salts.outputs.LOGGED_IN_KEY }}" \
            WP_NONCE_KEY="${{ steps.salts.outputs.NONCE_KEY }}" \
            WP_AUTH_SALT="${{ steps.salts.outputs.AUTH_SALT }}" \
            WP_SECURE_AUTH_SALT="${{ steps.salts.outputs.SECURE_AUTH_SALT }}" \
            WP_LOGGED_IN_SALT="${{ steps.salts.outputs.LOGGED_IN_SALT }}" \
            WP_NONCE_SALT="${{ steps.salts.outputs.NONCE_SALT }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: wordpress:latest
          outputs: type=docker,dest=/tmp/wordpress-image.tar

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          cat /tmp/wordpress-image.tar | ssh dokku@${{ secrets.DOKKU_HOST }} docker image load 
          ssh dokku@${{ secrets.DOKKU_HOST }} tags:deploy wordpress latest

      - name: Send deployment notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: WordPress deployment ${{ job.status }}
          SLACK_MESSAGE: 'WordPress has been ${{ job.status == "success" ? "successfully deployed" : "failed to deploy" }} to ${{ secrets.DOKKU_HOST }}'